### ISSUE TITLE
Assignment1 Problem 2-2 Spec 질문

### ISSUE THREAD

**Issue by junjinyong** [snu-sf-class/pp202302#10]
안녕하세요. 문제 2-2 설명에서 모순되는 것 같은 부분이 있어 질문 드립니다. 

다음 부분에서는 n-th prime이 [0, r] *[0, r]에 없을 수 있다고 이야기하고 있습니다. 
```
If there is no such value, return (0, 0)
```

그러나 다음 부분에서는 Gaussian prime이 [0, r] *[0, r]에 n개 이상 존재한다고 이야기하고 있습니다. 
```
We guarantee that the n-th prime is always in the sorted list
```

어떤 해석이 정확한지 알려주시면 감사하겠습니다.

**Comment by MerHS** [comment]
둘 다 맞습니다.
첫 번째는 만약 n-th prime이 없는 경우 (0,0)을 반환하라는 뜻이고
두 번째는 n-th prime이 없는 경우를 테스트하지 않겠다는 것입니다.

**Comment by junjinyong** [comment]
네 빠른 답변 감사합니다. n-th prime이 없는 경우 (0, 0)을 반환하는 것이 원칙이지만, 그런 경우를 고려하지 않아도 감점은 없다고 이해하면 될까요?

**Comment by MerHS** [comment]
말씀하신 말이 맞습니다.
