### ISSUE TITLE
2-3 FNoneOrMany, FOneOrMany의 Iist 순회순서 질문

### ISSUE THREAD

**Issue by cr0sh** [snu-sf-class/pp202302#37]
안녕하세요, 2-3의 `FNoneOrMany`, `FOneOrMany`의 `f`에 전해지는`IList`가 마지막에 얻은 원소를 순회시에 먼저 만나게 되는, 다시말해 LIFO 구조가 되어야 하는 게 맞나요? 한번 뒤집어서 사용했는데 테스트 케이스에서 정답과 뒤집힌 결과가 나와서 문의드립니다.

감사합니다.

**Comment by MerHS** [comment]
아닙니다. 기존의 문자열 순서에 맞게 들어가있어야 핮니다.

가령 “123”이 있으면 ICons(1, ICons(2, ICons(3, INil))) 같은 순으로 내보내야 합니다.

**Comment by cr0sh** [comment]
감사합니다. 제가 어디서 또다시 뒤집었는지 봐야겠네요...
