### ISSUE TITLE
Gitlab 비밀번호 관련 문의드립니다.

### ISSUE THREAD

**Issue by orbizzz** [snu-sf-class/pp202302#6]
안녕하세요, 혹시 제 학번이 2018-15196인데 비밀번호를 [====]으로 입력했더니 로그인이 되지 않는데 확인이 가능할까요?

**Comment by MerHS** [comment]
etl 상에 학생/청강생으로 등록이 되어 있어서 계정을 만들지 않았습니다.

혹시 후에 정식으로 수강신청을 하셨나요?

**Comment by orbizzz** [comment]
넵 청강신청을 먼저한 후에 수강신청도 정원외로 해서 학생/청강생 모두 보여지는것 같습니다.

**Comment by MerHS** [comment]
지금 계정을 생성하였으니 확인 바랍니다.

**Comment by orbizzz** [comment]
확인했습니다. 감사합니다.
