### ISSUE TITLE
프로젝트 3번 DummyIO의 var mutable 조작 허용 여부 문의

### ISSUE THREAD

**Issue by Grantzile** [snu-sf-class/pp202302#67]
프로젝트 3번 DummyIO를 확인하던 중 내부 input과 output이 var로 설정된 것을 확인했습니다.

extension 함수도 확인해봤는데, mutable한 방식 사용이 불가피해 보입니다. ReaderWriterImpl의 DummyIO 작동 시에 한해 input과 output 값을 수정해도 되나요?

**Comment by MerHS** [comment]
가능합니다.

뼈대코드에서 기본적으로 주어진 var 값은 변경해도 무방합니다.

**Comment by Grantzile** [comment]
감사합니다! :D
