### ISSUE TITLE
runIO 관련 질문

### ISSUE THREAD

**Issue by Grantzile** [snu-sf-class/pp202302#69]
(runIO x E) actually runs an IO action when E returns an IO action.
(i.e. IO[Value]). The result of the IO action is bound to x (i.e. The type
of x is Value.). You can also bind any value to x other than IO action. x
can be used in the following IO actions and the result E, but not in the
previous IO actions. (i.e. does not allow forward reference).

이 부분에서, runIO 의 forward reference를 허용하지 않는다는 부분 질문입니다.
runIO의 재귀호출 (즉 runIO 내부에서 자기 자신을 재귀호출) 하는 것도 forward reference로 취급하나요?

**Comment by MerHS** [comment]
E 내부에 x가 free variable로 (즉, 재귀함수 형태로) 들어가 있어서는 안됩니다. 
defIO/def 등을 사용할 때에 함수를 재귀함수로 선언하는 것은 가능합니다

**Comment by Grantzile** [comment]
그러면 runIO 외의 방법으로 defIO로 선언된 함수를 작동시키는 것이 가능한가요?
ex) runIO x (app someDefIOFunc) 외에 다른 방식으로 (app someDefIOFunc) 작동
(VIOThunk 반환, 이 상태에서 VIOThunk를 eval 내부에서 interpret 할 수 있어야 하나요?)
(구조상 안될 것 같기는 하지만 혹시나 해서 문의드립니다.)

+) 현재 제 구현 상 calculator에서 Int 범위를 넘어가면 overflow가 생기는데, 이런 부분도 BigInt 구현으로 해결해야 하나요?
+2) EIf는 0, 0.0의 경우 false, 그 외에는 true를 return하도록 되어 있습니다. Int / Float 외의 입력에 대해서도 true를 반환해야 하나요? (다른 자료형에 대해서는 언급이 없었습니다)

**Comment by MerHS** [comment]
runIO가 정상적으로 도는 경우는 runIO x E 에서 E의 evaluation 값이 VIOThunk인 경우 언제나 가능합니다. 즉, E가 정확히 app을 쓴 (app someDefIO) 라는 꼴이 아니라 대충 다른 꼴이라도 evaluation 값이 VIOThunk면 IO를 실행해야 합니다.

BigInt는 사용하지 마시고 (overflow 없음) boolean은 숫자로만 판단하신다고 생각하시면 됩니다

**Comment by Grantzile** [comment]
감사합니다. 잘 이해했습니다! XD
